  - name: cleanup git dir
    command: git clean -d -x -f chdir={{ app_root_dir }}

  - name: delete all mrt packages
    file: path="~/.meteorite/{{ item }}" state=absent
    with_items:
      - source
      - packages

  - name: reininstall mrt packages
    shell:
      chdir={{ app_path }}
      $(which mrt) update

  - name: create temp dir
    command: mktemp --directory
    register: temp_dir

  - name: build meteor app
    command:
      chdir={{ app_path }}
      meteor build --directory {{ temp_dir.stdout }} {% if app_mobile_server is defined %} --server {{ app_mobile_server }} {% endif %}
    register: meteor_build_result
    failed_when: "'Error:' in meteor_build_result.stdout or 'ERR!' in meteor_build_result.stdout"

  - name: check if bundleing was successful
    stat: path={{ temp_dir.stdout }}/bundle/main.js
    register: bundle_main_file

  - fail:
      msg: |
        Bundle is incomplete, this could have
        happened because the node process ran out of RAM.
        Please try running this playbook against a host that
        has more RAM or Swap Space
    when: not bundle_main_file.stat.exists

  - name: install npm packages
    npm: path={{ temp_dir.stdout }}/bundle/programs/server


  - name: clear target directory
    file: path={{ app_checkout_bundle_path }} state=absent
    sudo: yes

  - name: clear bundle dir
    file: path={{ app_checkout_bundle_path }} state=absent

  - name: ensure bundle dir exists
    file: path={{ app_checkout_bundle_path }} state=directory
    sudo: yes


  - name: deploy fresh bundle
    command: >
      mv
      {{ temp_dir.stdout }}/bundle
      {{ app_checkout_bundle_path }}/bundle
    sudo: yes

  - name: cleanup tmp dir
    tidy: path=/tmp age=2w recurse=true matches="tmp.*" rmdirs=yes

#  - name: cleanup bundle dir
#    tidy: path={{ app_bundle_dir }} age=2w
#    sudo: yes