---

- include_vars: "{{ansible_distribution}}.yml"

- name: Add APT key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5 validate_certs=False
  when: '"mongodb-org" in mongodb_package'

- name: Add APT repository
  apt_repository: repo="{{mongodb_repository}}" update_cache=yes
  when: '"mongodb-org" in mongodb_package'

- name: Install MongoDB package
  apt: pkg={{mongodb_package}} state=present
  
- name: Install additional packages
  apt:
    name: "{{ mongodb_additional_packages }}"