- hosts: mongoservers
  sudo: yes
  roles:
    - mongodb
    - telusdigital.logdna

- hosts: appservers
  sudo: yes
  #vars_files:
  #  - vars/main.yml
  #  - group_vars/{{ groupEnvConfigFile }}
  roles:
    - nodejs
    - nginx-passenger
    - meteorapp
    - telusdigital.logdna
  vars:
    nodejs_npm_modules: ["fibers", "meteorite"]

- hosts: loadbalancers
  sudo: yes
  roles:
    - ansible-haproxy
    - telusdigital.logdna


