---

# Add apt keys
- name: add key for ppa python repository
  apt_key: keyserver=keyserver.ubuntu.com id=DB82666C state=present
  become: yes
  become_user: root
  become_method: sudo

# Add extra repositories
- name: Add ppa python repository
  apt_repository: repo='deb http://ppa.launchpad.net/fkrull/deadsnakes-python2.7/ubuntu {{ ansible_distribution_release }} main' state=present update_cache=yes
  become: yes
  become_user: root
  become_method: sudo

# Update python version
- name: ensure python2.7 latest  is installed
  apt:
    pkg: python2.7
    state: latest
    install_recommends: no
  become: yes
  become_user: root
  become_method: sudo

- name: Install apt-transport-https
  sudo: true
  apt: name=apt-transport-https

- name: Node apt-key
  sudo: true
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Node sources list
  sudo: true
  template:
    src=nodesource.list.j2
    dest=/etc/apt/sources.list.d/nodesource.list

- name: Node apt-get install
  sudo: true
  apt:
    name=nodejs=8.*
    update_cache=yes
    state=present

- name: install build tools
  sudo: true
  apt: name=build-essential state=present

- name: install mrt
  npm:
    global=yes
    name=meteorite
    state=present
