haproxy_enable_ssl: no
haproxy_force_ssl: no
haproxy_enable_stats: no
haproxy_stats_username: someuser
haproxy_stats_password: somepassword
haproxy_stats_port: 21212
haproxy_config_use_appservers_eth: eth0
haproxy_maxconn: 200